[package]
name = "gravitation"
version = "0.1.0"
authors = ["Raphael Nestler <raphael.nestler@gmail.com>"]

[dev-dependencies]
rand = "0.3"
piston_window = "0.60"

[dev-dependencies.sdl2]
version = "*"
features = ["gfx"]
